Fetching table data
DalgoT4D/dbt-automation pull request #38
Opened 2023-10-25 16:45 UTC by Abhishek-N

2023-10-25 17:27 UTC, fatchat requested changes
what happens when you initialize a BigQueryClient with no parameters? my guess is that all existing code will break

in the PostgresClient constructor, what happens if you pass a dictionary containing the keys DBHOST etc. all existing scripts which do this will break

2023-10-26 10:10 UTC, Ishankoradia submitted a review, later dismissed

2023-10-26 10:15 UTC, Ishankoradia commented
> existing code will break

If we initialize the bigquery client with connection info as None, it will throw a value error. Same for postgres client
If we initialize the bigquery client with the wrong connection info, it will throw an exception `google.auth.exceptions..`. 
While the postgres client with throw `psycopg2.OperationalError`
So we can't move forward unless a valid client is initialized

2023-10-26 13:10 UTC, fatchat approved these changes

2023-10-26 13:10 UTC, merged